/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mageddo_jattach_Jattach */

#ifndef _Included_com_mageddo_jattach_Jattach
#define _Included_com_mageddo_jattach_Jattach
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mageddo_jattach_Jattach
 * Method:    load
 */
JNIEXPORT jint JNICALL Java_com_mageddo_jattach_Jattach_load
        (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     com_mageddo_jattach_Jattach
 * Method:    loadLibrary
 */
JNIEXPORT jint JNICALL Java_com_mageddo_jattach_Jattach_loadLibrary
        (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     com_mageddo_jattach_Jattach
 * Method:    attach
 */
JNIEXPORT jint JNICALL Java_com_mageddo_jattach_Jattach_attach
        (JNIEnv *, jclass, jint, jint, jobjectArray);

/*
 * Class:     com_mageddo_jattach_Jattach
 * Method:    loadJar
 */
JNIEXPORT jint JNICALL Java_com_mageddo_jattach_Jattach_loadJar
        (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
